#
server:
  port: 8080

spring:
#  datasource:
#    url: jdbc:mysql://192.168.1.18:3306/tain?serverTimezone=UTC&characterEncoding=UTF8
#    username: root
#    password: toor
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
  jpa:
#    show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: update
#
  h2:
    console:
      enabled: true
      path: /console
#
  devtools:
    livereload:
      enabled: true
#
  thymeleaf:
      cache: false
#
  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10
#
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 881218558153-ndr868i68rlofoo4l2gb488ksabi5q23.apps.googleusercontent.com
#            client-secret: kq6zIo0myJotHK5_0irhtYnW
#          facebook:
#            client-id: 465358593799840
#            client-secret: a37286e3dae00dcdce628f40dfe363f5
#custom:
#  oauth2:
#    kakao:
#      client-id: 1b8ff676ae01724ed77437f98d399543